/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.colors.themes.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Colors service. Represents a row in the &quot;theme_Colors&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.colors.themes.model.impl.ColorsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.colors.themes.model.impl.ColorsImpl}.
 * </p>
 *
 * @author user
 * @see Colors
 * @see com.colors.themes.model.impl.ColorsImpl
 * @see com.colors.themes.model.impl.ColorsModelImpl
 * @generated
 */
public interface ColorsModel extends BaseModel<Colors> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a colors model instance should use the {@link Colors} interface instead.
	 */

	/**
	 * Returns the primary key of this colors.
	 *
	 * @return the primary key of this colors
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this colors.
	 *
	 * @param primaryKey the primary key of this colors
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the color ID of this colors.
	 *
	 * @return the color ID of this colors
	 */
	public long getColorId();

	/**
	 * Sets the color ID of this colors.
	 *
	 * @param colorId the color ID of this colors
	 */
	public void setColorId(long colorId);

	/**
	 * Returns the color name of this colors.
	 *
	 * @return the color name of this colors
	 */
	@AutoEscape
	public String getColorName();

	/**
	 * Sets the color name of this colors.
	 *
	 * @param colorName the color name of this colors
	 */
	public void setColorName(String colorName);

	/**
	 * Returns the status of this colors.
	 *
	 * @return the status of this colors
	 */
	public boolean getStatus();

	/**
	 * Returns <code>true</code> if this colors is status.
	 *
	 * @return <code>true</code> if this colors is status; <code>false</code> otherwise
	 */
	public boolean isStatus();

	/**
	 * Sets whether this colors is status.
	 *
	 * @param status the status of this colors
	 */
	public void setStatus(boolean status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Colors colors);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Colors> toCacheModel();

	@Override
	public Colors toEscapedModel();

	@Override
	public Colors toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}